### ISSUE TITLE
[Feature Request] Ability to change the delay via a command

### ISSUE THREAD

**Issue by darkphan** [EmosewaPixel/GiftFromTheGods#1]
Would it be possible to add a command to adjust the delay between items? This is going to be fun to mess with :D

**Comment by TheLimePixel** [comment]
Which version are you referring to? On 1.14 it could be possible to change it per world load, but it definitely wouldn't update the config to keep it like that.

**Comment by darkphan** [comment]
Sorry, the one for 1.14 for sure.
